language: node_js

node_js:
  - "8"

cache:
  directories:
  - "node_modules"

services: mongodb

before_script:
  - npm install -g mocha
  - npm install

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
  repo_token:
    secure:

notifications:
  email: false
