language: node_js

node_js:
  - "8"

cache:
  directories:
  - "node_modules"

services: mongodb

before_script:
  - npm install -g mocha
  - npm install

script:
  - npm test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
  repo_token:
    secure: jryi7v9kNjh3Pjt8frvLOCxsnuuci6cfLHYMZAawqnp90u6QAP3SiH+5bQ29T/6ijb5DixzSxV7US1FIZAdx4NPtmfle3thexVXxf8VhNYSLKXxb6Qa5x2DUlDJrG7v+vyxgxE1TDwzPXF+0VUv7GtjZQOQJCIWIw237qPvXKIFfK1W5TV48LvRvXvEAOoecPG+iQd5S5mvGcc/df8DGw5jp+cI27eMavyMLsuSpdWekqboBYxaLzK/d+bU/CGE9rfvKPgQWqb5jGrGFq27e0Lwu9R4Ogn1pB0KhIT5E5X0WnnLYFuXg2zG5E5z0DIhW6lgWVl+GCqljzkOOQn56vuOChvOQEZA0sWHXQg5uqYXsHCzzlKISfwvMBOvaAiCjrNK4lII25AXMHWKmXPY6lPHik1Fixu2bEnUWfhXDzqcgvbeBh7IhOtUq0Mh9YREdbgIvFVDYJJbaa5teeK9CMl1I7Op9vcs1oraN1J5Ho39uq0L/47IvIMjfVs1DP4L2lBC1LEc0a23Q/WBDX6ltF5QSiCt/eNs7iv2htr1FdyZ7xI+RkNq5+hU0w7bWYFumKaJ8Nq1pz1qYJgHFlLN4+vzdPN1U8fzHl55WeyKgeIqftyUiuAlfxk91wwlqL8inQbc5kKsBEN+i4SfJ89rafNHra4nT2D8sZ2MLxaC4fUI

notifications:
  email: false
